cobradoronline/person/urls.py
from django.conf.urls import url, include
from django.views.i18n import JavaScriptCatalog

from cobradoronline.person.views import person_create, person_list, movement_create, person_view, person_turn, \
    person_return, GeneratePDF, movement_accountability, wall_copy

app_name = 'person'


urlpatterns = [
    url(r'novo/$', person_create, name='person_create'),
    url(r'consultar/(?P<id>\d+)/$', person_view, name='person_view'),
    url(r'prestacao-de-contas/$', movement_accountability, name='movement_accountability'),
    url(r'json-dump/$', wall_copy, name='wall_copy'),
    # url(r'api/data/$', get_data, name='api-data'),

    #url(r'recibo/$', generatePdf, name='generatepdf'),

    url(r'recibo/(?P<id>\d+)/$', GeneratePDF.as_view(), name='generatepdf'),
    url(r'lista/$', person_list, name='person_list'),
    url(r'giro/$', person_turn, name='person_turn'),
    url(r'retorno/$', person_return, name='person_return'),
    url(r'movimento/$', movement_create, name='movement_create'),

    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

cobradoronline/urls.py
""" cobradoronline URL Configuration """

from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    # cob    url(r'^foo/', include('foo.urls', namespace='foo')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^bolsa/', include('cobradoronline.bolsa.urls', namespace='bolsa')),
    url(r'^cliente/', include('cobradoronline.person.urls', namespace='person')),
    url(r'^bookings/', include('cobradoronline.bookings.urls', namespace='bookings')),
    url(r'^api/bookings/', include('cobradoronline.bookings.api.urls', namespace='booking-api')),
    path('admin/', admin.site.urls, name='administrador'),
]

cobradoronline/person/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

TRANSACTION_KIND = (
    ("in", "Cliente Pagou"),
    ("out", "Cliente Recebeu"),
    ("eaj", "Ajuste pagamento do Cliente"),
    ("saj", "Ajuste recebimento do Cliente")
)


class Person(models.Model):
    name = models.CharField('Nome',max_length=100)
    balance = models.DecimalField('Saldo', max_digits=10, decimal_places=2)
    user = models.ForeignKey(User, related_name='Person_Usuário', on_delete=models.CASCADE)
    public_place = models.CharField('Logradouro',max_length=150)
    number = models.CharField('Número',max_length=150)
    city = models.CharField('Cidade', max_length=150)
    state = models.CharField('Estado', max_length=150)
    zipcode = models.CharField('Cep', max_length=10)
    neighborhood = models.CharField('Bairro',max_length=50)
    date_of_turn = models.DateField('Dt. Giro.')
    date_return = models.DateField('Dt. Retorno.', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Pessoas'
        verbose_name = 'Pessoa'
        ordering = ('name',)

    # def stock_avaliable(self):
    #     itens_nota = Movimento.objects.select_related('person').all().order_by("created")
    #     total_avaliable = 0
    #
    #     for transaction in itens_nota:
    #         if transaction.person.transaction_kind == 'in' or transaction.person.transaction_kind == 'eaj':
    #             total_avaliable += transaction.balance
    #         else:
    #             total_avaliable -= transaction.balance
    #
    #     return total_avaliable

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('person:person_view', args=[str(self.id)])


class Movimento(models.Model):
    person = models.ForeignKey('person.Person', related_name='person_item',on_delete=models.CASCADE)
    transaction_kind = models.CharField('Tipo Movimento', max_length=4, choices=TRANSACTION_KIND)
    value_moved = models.DecimalField('Valor Movimento', max_digits=10, decimal_places=2)
    created = models.DateField('created')
    modified = models.DateTimeField('modified', auto_now=True)
    date_return = models.DateField('Dt. Retorno..')
    user = models.ForeignKey(User, related_name='Movimento_Usuário', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Movimento'
        verbose_name_plural = 'Movimentos'
        # ordering = ('person',)


def post_save_movimento(sender, instance, created,  **kwargs):
    if created:
        if instance.transaction_kind == 'in' or instance.transaction_kind == 'eaj':
            instance.person.balance += instance.value_moved
            instance.person.date_return = instance.date_return
            instance.person.save()
        else:
            instance.person.balance -= instance.value_moved
            instance.person.date_return = instance.date_return
            instance.person.save()
    else:
        instance.person.balance -= instance.person.balance
        instance.person.balance += instance.person.balance # instance.person.stock_avaliable()
        instance.person.date_return = instance.date_return
        instance.person.save()


models.signals.post_save.connect(
    post_save_movimento, sender=Movimento, dispatch_uid='post_save_movimento'
)

cobradoronline/person/forms.py
from django import forms
from django.contrib.auth.models import User

from cobradoronline.person.models import Person, Movimento
from django.contrib.admin.widgets import AdminTextInputWidget


# default='Brasil', editable=False
class PersonForm(forms.ModelForm):
    name = forms.CharField(label='Nome', required=True, widget=AdminTextInputWidget(attrs={'class':'form-control input-lg'}))
    public_place = forms.CharField(label='Endereço completo', widget=AdminTextInputWidget(attrs={'class':'form-control input-lg'}))
    number = forms.CharField(label='Número', widget=AdminTextInputWidget(attrs={'class':'form-control input-lg'}))
    city = forms.CharField(label='Cidade', widget=AdminTextInputWidget(attrs={'class':'form-control input-lg'}))
    state = forms.CharField(label='Estado', widget=AdminTextInputWidget(attrs={'class':'form-control input-lg'}))
    zipcode = forms.CharField(label='Cep', widget=AdminTextInputWidget(attrs={'class':'form-control input-lg'}))
    neighborhood = forms.CharField(label='Bairro', widget=AdminTextInputWidget(attrs={'class':'form-control input-lg'}))
    balance = forms.DecimalField(label='Saldo', widget=AdminTextInputWidget(attrs={'class': 'form-control input-lg'}))
    date_of_turn = forms.DateField(label='Dt. Giro', widget=forms.TextInput(attrs={'class': 'form-control input-lg'}))
    date_return = forms.DateField(required=False)
    # class="form-control input-lg"

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        self.fields['balance'].localize = True
        self.fields['balance'].widget.is_localized = True

    def clean_name(self):
        name = self.cleaned_data['name']
        return name.upper()

    class Meta:
        model = Person
        exclude = ['date_return', 'user']
        fields = '__all__'
        ordering = ('name',)


TRANSACTION_KIND = (
    ("---", "---------"),
    ("in", "Cliente Pagou"),
    ("out", "Cliente Recebeu"),
    ("eaj", "Ajuste pagamento do Cliente"),
    ("saj", "Ajuste recebimento do Cliente")
)


class MovimentoForm(forms.ModelForm):
    person = forms.ModelChoiceField(label='Pessoa', widget=forms.Select(attrs={'class': 'form-control'}), required=True,
                                    queryset=Person.objects.all())

    transaction_kind = forms.ChoiceField(label='Tipo Movimento',
                                         widget=forms.Select(attrs={'class': 'form-control'}),
                                         required=True, choices=TRANSACTION_KIND)
    value_moved = forms.DecimalField(label='Valor Movimentado',
                                     widget=AdminTextInputWidget(attrs={'class': 'form-control input-lg'}),
                                     max_digits=10,
                                     decimal_places=2)
    created = forms.DateField(label='Dt. Movimento',
                              widget=forms.TextInput(attrs={'class': 'form-control input-lg'}))
    date_return = forms.DateField(label='Dt. Retorno',
                                  widget=forms.TextInput(attrs={'class': 'form-control input-lg'}))

    # def __init__(self, user,  *args, **kwargs):
    #     super(MovimentoForm, self).__init__(*args, **kwargs)
    #     self.fields['moved'].widget.is_localized = True

    def __init__(self, user_id, *args, **kwargs):
        super().__init__(*args, **kwargs)

        print(user_id)

        # user_id ta sendo passado via GET da VIEW, assim pego o id do usuario para meu queryset.
        self.fields['person'].queryset = Person.objects.filter(user_id=user_id)

        self.fields['value_moved'].localize = True
        self.fields['value_moved'].widget.is_localized = True

        """
        A variavel pk acima vem da view atendimento_create(request, pk): onde envio esse valor
        no GET na linha 29
        context = {'form': AtendimentoForm(pk)}
        """

    class Meta:
        model = Movimento
        exclude = ['modified', 'user']
        fields = '__all__'
        # ordering = ('person',)

cobradoronline/person/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, request
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.template.loader import get_template
from django import template

from django.utils.timezone import now
from datetime import datetime

from django.views.generic.dates import timezone_today

from cobradoronline.person.forms import PersonForm, MovimentoForm
from cobradoronline.person.models import Person, Movimento

from django.views.generic import View

from cobradoronline.utils import render_to_pdf


class GeneratePDF(View):
    def get(self, request, id, *args, **kwargs):
        template = get_template('recibo.html')

        person = Person.objects.get(id=id)
        movements = Movimento.objects.filter(person_id=id)

        context = {
            'person': person,
            'movements': movements
        }

        html = template.render(context)
        pdf = render_to_pdf('recibo.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("Not found")


def person_create(request):
    if request.method == 'POST':
        form = PersonForm(request.POST)

        if form.is_valid():
            print('<<<<==== FORM VALIDO ====>>>>')
            new = form.save(commit=False)
            new.user = request.user
            new.save()
            form.save_m2m()

            return HttpResponseRedirect('/cliente/lista/')
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')
            return render(request, 'person_create.html', {'form': form})
    else:
        context = {'form': PersonForm()}
        return render(request, 'person_create.html', context)


def person_return(request):
    q = request.GET.get('searchInput')

    if q:
        persons = Person.objects.filter(name__icontains=q, date_return__lte=now())
    else:
        persons = Person.objects.filter(date_return__lte=now())
    context = {'persons': persons}
    print(context)
    return render(request, 'person_return.html', context)


register = template.Library()


@register.simple_tag
def total_venda(request):
    q = request.GET.get('searchInput')
    if q:
        date_query = datetime.strptime(q, '%d/%m/%Y').date()
        return Movimento.objects.filter(created__contains=date_query,
                                        transaction_kind__icontains='out').aggregate(total=Sum('value_moved'))
    else:
        # date_query = now().year, now().month, now().day
        return Movimento.objects.filter(created__lt=timezone_today(),
                                        transaction_kind__icontains='out').aggregate(Sum('value_moved'))


def movement_accountability(request, i=0):
    q = request.GET.get('searchInput')
    if q:
        date_query = datetime.strptime(q, '%d/%m/%Y').date()

        # moviments = Movimento.objects.filter(created__contains=date_query)
        moviments = Movimento.objects.select_related().\
            filter(created__contains=date_query).\
            values('user__username', 'transaction_kind').annotate(Sum('value_moved'))

        saida = Movimento.objects.filter(created__contains=date_query,
                                         transaction_kind__icontains='out').aggregate(Sum('value_moved'))
        compra = Movimento.objects.filter(created__contains=date_query,
                                          transaction_kind__icontains='in').aggregate(Sum('value_moved'))

        moviments.total_venda = saida['value_moved__sum']
        moviments.total_compra = compra['value_moved__sum']

    else:
        moviments = Movimento.objects.select_related().\
            filter(created__contains=timezone_today()).\
            values('user__username', 'transaction_kind').annotate(Sum('value_moved'))

        saida = Movimento.objects.filter(created__contains=timezone_today(),
                                         transaction_kind__icontains='out').aggregate(Sum('value_moved'))
        compra = Movimento.objects.filter(created__contains=timezone_today(),
                                          transaction_kind__icontains='in').aggregate(Sum('value_moved'))

        moviments.total_venda = saida['value_moved__sum']
        moviments.total_compra = compra['value_moved__sum']

    context = {'moviments': moviments}
    return render(request, 'moviment_accountability.html', context)


def movement_accountability2(request, i=0):
    q = request.GET.get('searchInput')
    if q:
        date_query = datetime.strptime(q, '%d/%m/%Y').date()
        moviments = Movimento.objects.filter(created__contains=date_query)
        saida = Movimento.objects.\
            filter(created__contains=date_query, transaction_kind__icontains='out').aggregate(Sum('value_moved'))
        compra = Movimento.objects.\
            filter(created__contains=date_query, transaction_kind__icontains='in').aggregate(Sum('value_moved'))
        moviments.total_venda = saida['value_moved__sum']
        moviments.total_compra = compra['value_moved__sum']

        print(saida['value_moved__sum'])
    else:
        moviments = Movimento.objects.filter(created__contains=timezone_today())
        saida = Movimento.objects.\
            filter(created__contains=timezone_today(), transaction_kind__icontains='out').aggregate(Sum('value_moved'))
        compra = Movimento.objects.\
            filter(created__contains=timezone_today(), transaction_kind__icontains='in').aggregate(Sum('value_moved'))
        from django.db.models import Count

        moviments.total_venda = saida['value_moved__sum']
        moviments.total_compra = compra['value_moved__sum']

    context = {'moviments': moviments}
    return render(request, 'moviment_accountability.html', context)


def wall_copy(request):
    posts = Movimento.objects.values('person__name', 'transaction_kind').\
        annotate(Sum('value_moved'), Count('transaction_kind')).values()

    return JsonResponse(posts, safe=False)


def person_turn(request):
    q = request.GET.get('searchInput')

    if q:
        print(q)
        persons = Person.objects.filter(name__icontains=q, date_of_turn__lte=now())
    else:
        persons = Person.objects.filter(date_of_turn__lte=now())
    context = {'persons': persons}
    print(context)
    return render(request, 'person_turn.html', context)


@login_required
def person_list(request):
    q = request.GET.get('searchInput')

    if request.user.id == 2:
        if q:
            print(q)
            persons = Person.objects.filter(name__icontains=q)
        else:
            persons = Person.objects.all()
        context = {'persons': persons}
    else:
        if q:
            print(q)
            persons = Person.objects.filter(name__icontains=q, user__in=[request.user])
        else:
            persons = Person.objects.filter(user__in=[request.user])
        context = {'persons': persons}
    print(context)
    return render(request, 'person_list.html', context)


def person_view(request, id):
    person = Person.objects.get(id=id)
    movements = Movimento.objects.filter(person_id=id)

    context = {
        'person':person,
        'movements':movements
    }
    return render(request, 'person_view.html', context)


def movement_create(request):

    user_id = request.user
    print(request.user)

    if request.method == 'POST':
        form = MovimentoForm(user_id, request.POST)

        if form.is_valid():
            print('<<<<==== FORM VALIDO ====>>>>')
            new = form.save(commit=False)
            new.user = request.user
            new.save()
            form.save_m2m()

            return HttpResponseRedirect('/cliente/lista/')
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')
            print(form)
            return render(request, 'movement_create.html', {'form': form})
    else:
        # user_id no GET ta sendo passado para o forms.py, assim pego o id do usuario para meu queryset.
        context = {'form': MovimentoForm(user_id)}
        return render(request, 'movement_create.html', context)

cobradoronline/person/templates/charts.html
{% extends "index.html" %}


{% block content %}
        <!--{% block jquery %}-->
        <!--<script>-->
            <!--var endpoint = '/cliente/api/data/'-->
            <!--$.ajax({-->
                <!--method = "GET",-->
                <!--url: endpoint,-->
                <!--success: function(data){-->
                    <!--console.log(data)-->
                <!--},-->
                <!--error: function(error_data){-->
                    <!--console.log("error")-->
                    <!--console.log(error_data)-->
                <!--}-->
            <!--})-->
        <!--</script>-->
        <!--{% endblock %}-->

    <div class="row">
        <!-- BEGIN ALERT - REVENUE -->
        <div class="col-md-6 col-sm-6" url-endpoint='{% url "api-data" %}'>
            teu cú
        </div><!--end .col -->
    </div>
{% endblock %}

cobradoronline/person/templates/movement_create.html
{% extends "index.html" %}
{% block content %}
<!-- BEGIN VERTICAL FORM -->
    <div class="col-md-12">
        <form class="create-form" url="{% url 'person:movement_create' %}" method="post">
            {% csrf_token %}
            <div class="card">
                <div class="card-head style-primary">
                    <header>Movimento</header>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                {{form.person.errors}}
                                {{form.person}}
                                <label for="{{ form.person.id_for_label}}">{{form.person.label}}</label>
                            </div>
                        </div>

                        <div class="input-group date col-sm-4" id="datepicker2">
                             <div class="input-group-content">
                                {{form.created.errors}}
                                {{form.created}}
                                <label for="{{form.created.id_for_label}}"TRANSACTION_KIND>{{form.created.label}}</label>
                            </div>
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>

                    <br/>

                    <div class="row">
                        <div class="col-sm-4">
                            <div class="form-group">
                                {{form.transaction_kind.errors}}
                                {{form.transaction_kind}}
                                <label for="{{ form.transaction_kind.id_for_label}}">{{form.transaction_kind.label}}</label>
                            </div>
                        </div>


                        <div class="col-sm-4">
                            <div class="form-group">
                                {{form.value_moved.errors}}
                                {{form.value_moved}}
                                <label for="{{ form.value_moved.id_for_label}}">{{form.value_moved.label}}</label>
                            </div>
                        </div>


                        <div class="input-group date col-sm-4" id="datepicker1">
                             <div class="input-group-content">
                                {{form.date_return.errors}}
                                {{form.date_return}}
                                <label for="{{form.date_return.id_for_label}}">{{form.date_return.label}}</label>
                            </div>
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>



                    <br/>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                {{form.user.errors}}
                                {{form.user}}
                                <label for="{{ form.user.id_for_label}}">{{form.user.label}}</label>
                            </div>
                        </div>

                    </div>



                    <div class="card-actionbar">
                        <div class="card-actionbar-row">
                            <button type="submit" class="btn btn-flat btn-primary ink-reaction">Concluir</button>
                        </div>
                    </div>
        </form>
    </div><!--end .col -->

<!-- END VERTICAL FORM -->

{% endblock content %}

{% block extrajs %}
    <script>
        $('#multi-select').multiSelect({});
        $('#datepicker1').datepicker({
            format: 'dd/mm/yyyy'
            //,startDate: '-3d'
        });

        $('#datepicker2').datepicker({
            format: 'dd/mm/yyyy'
            //,startDate: '-3d'
        });
        $('#select').select2({});
    </script>
{% endblock extrajs %}

cobradoronline/person/templates/person_create.html
{% extends "index.html" %}

{% block content %}

    <div class="col-lg-offset-1 col-md-10">
        <form class="create-form" url="{% url 'person:person_create' %}" method="post">
            {% csrf_token %}
            <div class="card">
                <div class="card-head style-primary">
                    <header>Cadastro de Cliente</header>
                </div>

                <div class="card-body">
                    <div class="row">

                        <div class="col-sm-8">
                            <div class="form-group">
                                {{form.name.errors}}
                                {{form.name}}
                                <label for="{{ form.name.id_for_label}}">{{form.name.label}}</label>
                            </div>
                        </div>

                        <div class="form-group control-width-normal col-sm-4">
                            <div class="input-group date" id="datepicker">
                                <div class="input-group-content">
                                    {{form.date_of_turn.errors}}
                                    {{form.date_of_turn}}
                                    <label for="{{form.date_of_turn.id_for_label}}">{{form.date_of_turn.label}}</label>
                                </div>
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            </div>
                        </div><!--end .form-group -->
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{form.zipcode.errors}}
                                {{form.zipcode}}
                                <label for="{{ form.zipcode.id_for_label}}">{{form.zipcode.label}}</label>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                {{form.number.errors}}
                                {{form.number}}
                                <label for="{{ form.number.id_for_label}}">{{form.number.label}}</label>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                {{form.balance.errors}}
                                {{form.balance}}
                                <label for="{{ form.balance.id_for_label}}">{{form.balance.label}}</label>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-8">
                            <div class="form-group">
                                {{form.public_place.errors}}
                                {{form.public_place}}
                                <label for="{{ form.public_place.id_for_label}}">{{form.public_place.label}}</label>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                {{form.neighborhood.errors}}
                                {{form.neighborhood}}
                                <label for="{{ form.neighborhood.id_for_label}}">{{form.neighborhood.label}}</label>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                {{form.city.errors}}
                                {{form.city}}
                                <label for="{{ form.city.id_for_label}}">{{form.city.label}}</label>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                {{form.state.errors}}
                                {{form.state}}
                                <label for="{{ form.state.id_for_label}}">{{form.state.label}}</label>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                {{form.user.errors}}
                                {{form.user}}
                                <label for="{{ form.user.id_for_label}}">{{form.user.label}}</label>
                            </div>
                        </div>
                    </div>
                </div><!--end .card-body -->

                <div class="card-actionbar">
                    <div class="card-actionbar-row">
                        <button type="submit" class="btn btn-flat btn-primary ink-reaction">Concluir</button>
                    </div>
                </div>
            </div><!--end .card -->
            <em class="text-caption">Vertical layout with static labels</em>
        </form>
    </div><!--end  -->
    <!-- END VERTICAL FORM FLOATING LABELS -->

    <script type="text/javascript">
        cep_value = document.getElementById("id_zipcode");
        logradouro = document.getElementById("id_public_place");
        bairro = document.getElementById("id_neighborhood");
        localidade = document.getElementById("id_city");
        uf = document.getElementById("id_state");
        balance = '0'
        //country = document.getElementById("id_country");
        // logradouro.readOnly = true;
        // bairro.readOnly = true;
        // localidade.readOnly = true;
        // uf.readOnly = true;
       //country.readOnly = true;
        cep_value.addEventListener("keyup",function(event){
            if (this.value.length == 8){
                headers = new Headers();
                headers.append("Access-Control-Allow-Origin","*")
                data = fetch("https://viacep.com.br/ws/"+ this.value +"/json/",headers)
                    .then(function(response){
                        Promise.resolve(response.json()).then(function(value){
                            logradouro.value = value.logradouro;
                            bairro.value = value.bairro;
                            localidade.value = value.localidade;
                            uf.value = value.uf;
                            balance.value = 0;
                            //country.value = 'Brasil';
                            // Adiciona a classe 'active' aos campos já preenchidos, isto faz com que o
                            // 'label' do campo fique 'alto'
                            document.getElementById("id_neighborhood_container").childNodes[3].className='active';
                            document.getElementById("id_public_place_container").childNodes[3].className='active';
                            document.getElementById("id_city_container").childNodes[3].className='active';
                            document.getElementById("id_state_container").childNodes[3].className='active';
                            document.getElementById("id_balance_container").childNodes[3].className='active';
                        });
                    }).catch(function(error){
                        console.log(error);
                    });
            }
        });


    </script>
{% endblock content %}

{% block extrajs %}
    <script>
        $('#multi-select').multiSelect({});
        $('#datepicker').datepicker({
            format: 'dd/mm/yyyy'
            //,startDate: '-3d'
        });
        $('#select').select2({});
    </script>
{% endblock extrajs %}