cobradoronline/bookings/api/urls.py
from django.conf.urls import url

app_name = 'bookings-api'

from .views import (
    PostListAPIView,
    PostListFeriadoAPIView,
    PostDetailAPIView,
    PostDeleteAPIView,
    PostUpdateAPIView,
    PostCreateAPIView,
    PostList2APIView, PostUpdate2APIView)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='listapi'),
    url(r'^(?P<pk>\d+)/$',PostDetailAPIView.as_view(),name='detail'),
    url(r'^(?P<pk>\d+)/delete/$',PostDeleteAPIView.as_view(),name='delete'),
    url(r'^(?P<pk>\d+)/edit/$',PostUpdateAPIView.as_view(),name='update'),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^feriado/$', PostListFeriadoAPIView.as_view(), name='feriado'),
    #url(r'^(?P<slug>[\W-]+)/$',PostDetailAPIView.as_view(),name='detail')

    url(r'^list/$', PostList2APIView.as_view(), name='listapi2'),
        url(r'^(?P<pk>\d+)/edita/$', PostUpdate2APIView.as_view(), name='update2'),
]

cobradoronline/bookings/urls.py
from django.conf.urls import url, include
from django.views.i18n import JavaScriptCatalog

from cobradoronline.bookings.views import bookings_list, scheduling, scheduling_edit, bookings_create, bookings_update

app_name = 'bookings'

urlpatterns = [
    url(r'listagem/$', bookings_list, name='bookings_list'),
    url(r'agendamento/$', scheduling, name='scheduling'),
    url(r'agendamento/novo/$', bookings_create, name='bookings_create'),
    url(r'agendamento/editar/(?P<id_booking>\d+)/$', bookings_update, name='bookings_update'),
    url(r'reserva/(?P<id_booking>\d+)/update/$', scheduling_edit, name='scheduling_edit'),
    
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

cobradoronline/urls.py
""" cobradoronline URL Configuration """

from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    # cob    url(r'^foo/', include('foo.urls', namespace='foo')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^bolsa/', include('cobradoronline.bolsa.urls', namespace='bolsa')),
    url(r'^cliente/', include('cobradoronline.person.urls', namespace='person')),
    url(r'^bookings/', include('cobradoronline.bookings.urls', namespace='bookings')),
    url(r'^api/bookings/', include('cobradoronline.bookings.api.urls', namespace='booking-api')),
    path('admin/', admin.site.urls, name='administrador'),
]

cobradoronline/bookings/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Booking(models.Model):
    # CHOICES NO MODELS VAI TER UMA LISTAGEM NO ADMIN
    CORES_CHOICES = (
        ('red', 'red'),
        ('blue', 'blue'),
        ('green', 'green'),
        ('black', 'black'),
        ('yellow', 'yellow')
    )

    allday = models.BooleanField('Dia inteiro', default=False)
    title = models.CharField('evento', max_length=128)
    start = models.DateTimeField('inicio')
    end = models.DateTimeField('fim')
    created_on = models.DateTimeField('solicitado em', default=timezone.now)
    authorized = models.BooleanField('autorizado', default=False)
    editable = models.BooleanField('Editavel', default=True) #True permite o user arrastar e soltar para qualquer data, False não permite
    color = models.CharField('cor', max_length=15, choices=CORES_CHOICES, default='blue')
    overlap = models.BooleanField('Sobrepor', default=True) #Áreas vermelhas onde nenhum evento pode ser descartado (Período que não pode receber nenhum agendamento)
    holiday = models.BooleanField('Feriado')
    participants = models.ManyToManyField(User, blank=True, related_name="participants")
    #rendering: 'background' Áreas onde "Reunião" deve ser descartado (Sem permissão de Incluir/Editar/Excluir o evendo)
    class Meta:
        verbose_name = 'reserva'
        verbose_name_plural = 'reservas'
        ordering = ('-start',)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('scheduling:agendamento')

cobradoronline/bookings/forms.py
from django import forms

from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.models import User
#from material import Layout, Fieldset, Row, Span6

from cobradoronline.bookings.models import Booking


class BookingsForm(forms.ModelForm):
    allday = forms.BooleanField(label='Dia inteiro', required=False)
    title = forms.CharField(label='Titulo do agendamento', widget=forms.TextInput(attrs={'class': 'form-control'}))
    start = forms.DateTimeField(label='Inicia em...', widget=forms.TextInput(attrs={'class': 'form-control'}))
    end = forms.DateTimeField(label='Termina em...', widget=forms.TextInput(attrs={'class': 'form-control'}))
    #created_on = forms.DateTimeField(label='Criado em...')
    authorized = forms.BooleanField(label='Autorizado', required=False)
    editable = forms.BooleanField(label='Editavel', required=False)
    # ABAIXO, CHOICES NO FORMS VAI TER UMALISTAGEM NO TEMPLATE
    color = forms.ChoiceField(label='Cor', choices=(('blue', 'blue'),
                                                    ('red', 'red'),
                                                    ('green', 'green'),
                                                    ('black', 'black')), widget=forms.Select(attrs={'class': 'form-control select2-list'}))
    #form-control select2-list
    overlap = forms.BooleanField(label='Sobrepor?', required=False)
    holiday = forms.BooleanField(label='Feriado?', required=False)
    participants = forms.ModelMultipleChoiceField(label='Participantes', queryset=User.objects.all(), widget=FilteredSelectMultiple("Participantes", is_stacked=False, attrs={'id':'multi-select'}))

    class Meta:
        model = Booking
        exclude = ['created_on']
        fields = '__all__'

    # layout = Layout(
    #     Fieldset('Inclua uma agenda',
    #              Row('title', ),
    #              Row('start','end', 'color'),
    #              Row(Span6('holiday'),Span6('authorized'), ),
    #              Row(Span6('editable'), Span6('allday')),
    #              Row('overlap'),
    #              Row('participants')
    #              )
    # )

cobradoronline/bookings/api/views.py
from django.shortcuts import redirect
from rest_framework.generics import (
    DestroyAPIView,
    ListAPIView,
    UpdateAPIView,
    RetrieveAPIView,
    CreateAPIView, get_object_or_404)
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response

from cobradoronline.bookings.models import Booking
from cobradoronline.bookings.serializer import BookingSerializer
from .serializers import (BookingListSerializer,
                          BookingDetailSerializer,
                          BookingCreateUpdateSerializer, BookingListFeriadoSerializer)


class PostCreateAPIView(CreateAPIView):
    queryset = Booking.objects.all()
    serializer_class = BookingCreateUpdateSerializer

class PostDetailAPIView(RetrieveAPIView):
    queryset = Booking.objects.all()
    serializer_class = BookingDetailSerializer
    # lookup_field = 'user'


class PostUpdateAPIView(UpdateAPIView):
    queryset = Booking.objects.all()
    serializer_class = BookingCreateUpdateSerializer
    lookup_field = 'pk'


class PostDeleteAPIView(DestroyAPIView):
    queryset = Booking.objects.all()
    serializer_class = BookingDetailSerializer
    lookup_field = 'pk'


class PostListAPIView(ListAPIView):
    queryset = Booking.objects.all()
    serializer_class = BookingListSerializer

class PostListFeriadoAPIView(ListAPIView):
    queryset = Booking.objects.filter(holiday=True)
    serializer_class = BookingListFeriadoSerializer

#------------------------------------------------------------------------------------


class PostList2APIView(ListAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'profile_list.html'

    def get(self, request):
        queryset = Booking.objects.all()
        return Response({'bookings': queryset})

class PostUpdate2APIView(UpdateAPIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'profile_detail.html'

    def get(self, request, pk):
        booking = get_object_or_404(Booking, pk=pk)
        serializer = BookingSerializer(booking)
        return Response({'serializer': serializer, 'booking': booking})

    def post(self, request, pk):
        booking = get_object_or_404(Booking, pk=pk)
        serializer = BookingSerializer(booking, data=request.data)
        if not serializer.is_valid():
            return Response({'serializer': serializer, 'booking': booking})
        serializer.save()
        return redirect('profile-list')

cobradoronline/bookings/views.py
from datetime import date

from django.http import HttpResponse, JsonResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from rest_framework.viewsets import ModelViewSet

from cobradoronline import bookings
from cobradoronline.bookings.forms import BookingsForm
from cobradoronline.bookings.models import Booking
from cobradoronline.bookings.serializer import BookingSerializer

class BookingViewSet(ModelViewSet):
    queryset = Booking.objects.all()
    serializer_class = BookingSerializer


def bookings_list(request):
    selected_date = date.today()
    return list_date(request) #return list_date(request, selected_date.year, selected_date.month)


def list_date(request):
    return render(request, 'bookings/bookings_list.html') #def list_date(request, year, month):

# def bookings_create(request):
# 	if request.method == 'POST':
# 		form = BookingsForm(request.POST)
# 	else:
# 		form = BookingsForm()
# 	return save_all(request,form,'book_create.html')


def save_bookings_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            bookings = Booking.objects.all()
            data['html_book_list'] = render_to_string('bookings/includes/partial_bookings_list.html', {
                'books': bookings
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

def bookings_create(request):
    if request.method == 'POST':
        form = BookingsForm(request.POST)
    else:
        form = BookingsForm()
    return save_bookings_form(request, form, 'bookings/includes/partial_book_create.html')


def bookings_update(request, pk):
    bookings = get_object_or_404(Booking, pk=pk)
    if request.method == 'POST':
        form = BookingsForm(request.POST, instance=bookings)
    else:
        form = BookingsForm(instance=bookings)
    return save_bookings_form(request, form, 'bookings/includes/partial_book_update.html')


def book_delete(request, pk):
    book = get_object_or_404(Booking, pk=pk)
    data = dict()
    if request.method == 'POST':
        bookings.delete()
        data['form_is_valid'] = True
        books = Booking.objects.all()
        data['html_bookings_list'] = render_to_string('bookings/includes/partial_book_list.html', {
            'bookings': books
        })
    else:
        context = {'bookings': bookings}
        data['html_form'] = render_to_string('bookings/includes/partial_book_delete.html', context, request=request)
    return JsonResponse(data)


#-----------------------------------------------------------------------------------------------------
def bookings_create1(request):
    data = dict()

    if request.method == 'POST':
        form = BookingsForm(request.POST)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    else:
        form = BookingsForm()
    context = {'form': form}
    data['html_form'] = render_to_string('bookings_create_form.html',
        context,
        request=request
    )
    return JsonResponse(data)


def scheduling(request):
    if request.method == 'POST':
        form = BookingsForm(request.POST)

        if form.is_valid():
            print('<<<<==== FORM VALIDO ====>>>>')
            new = form.save(commit=False)
            new.save()
            form.save_m2m()

            return HttpResponseRedirect('bookings/listagem/')
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')
            return render(request, 'bookings/scheduling_form.html', {'form':form})
    else:
        context = {'form': BookingsForm()}
        return render(request, 'bookings/scheduling_form.html', context)


def scheduling_edit(request, id_booking):
    booking = Booking.objects.get(id=id_booking)
    if request.method == 'GET':
        form = BookingsForm(instance=booking)
    else:
        form = BookingsForm(request.POST, instance=booking)
        if form.is_valid():
            new = form.save(commit=False)
            new.save()
            form.save_m2m()
        return HttpResponseRedirect('bookings/listagem/'+id_booking)
    return render(request, 'bookings/scheduling_form.html', {'form': form})

cobradoronline/bookings/templates/bookings_create.html
    <!-- BEGIN VERTICAL FORM FLOATING LABELS -->
    <div class="row"> <!-- col-lg-offset-0 -->
        <div class="col-md-12">
            <form class="create-form" url="{% url 'bookings:bookings_create' %}" method="post">
                {% csrf_token %}

                        <label class="card-body floating-label col-md-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        {{form.title.errors}}
                                        {{form.title}}
                                        <label for="{{ form.title.id_for_label}}">{{form.title.label}}</label>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="input-daterange input-group col-sm-12" id="datepicker">
                                    <div class="input-group-content">
                                        {{form.start.errors}}
                                        {{form.start}}
                                        <label for="{{form.start.id_for_label}}">{{form.start.label}}</label>
                                    </div>

                                    <span class="input-group-addon">to</span>

                                    <div class="input-group-content">
                                        {{form.end.errors}}
                                        {{form.end}}
                                        <label for="{{form.end.id_for_label}}">{{form.end.label}}</label>
                                    </div>
                                </div>
                            </div>

                            <label class="checkbox checkbox-styled">

                                <label for="{{ form.holiday.id_for_label }}" class="col-sm-3">
                                    {{ form.holiday }}
                                    {{ form.holiday.errors }}
                                    <span>{{ form.holiday.label }}</span>
                                </label>

                                <label for="{{ form.overlap.id_for_label }}" class="col-sm-3">
                                    {{ form.overlap }}
                                    {{ form.overlap.errors }}
                                    <span>{{ form.overlap.label }}</span>
                                </label>

                                <label for="{{ form.allday.id_for_label }}" class="col-sm-3">
                                    {{ form.allday }}
                                    {{ form.allday.errors }}
                                    <span>{{ form.allday.label }}</span>
                                </label>

                                <label for="{{ form.editable.id_for_label }}" class="col-sm-3">
                                    {{ form.editable }}
                                    {{ form.editable.errors }}
                                    <span>{{ form.editable.label }}</span>
                                </label>

                                <label for="{{ form.authorized.id_for_label }}" class="col-sm-3">
                                    {{ form.authorized }}
                                    {{ form.authorized.errors }}
                                    <span>{{ form.authorized.label }}</span>
                                </label>
                            </label>

                            <!-- BEGIN MULTI-SELECT -->
                            <div class="row">
                                <div class="col-lg-offset-0 col-md-12">
                                        {{form.color}}
                                </div><!--end .col -->
                            </div><!--end .row -->
                             <!-- END MULTI-SELECT -->


                            <!-- BEGIN MULTI-SELECT -->
                            <div class="row">
                                <span>{{form.participants.label}}</span>
                                <div class="col-lg-offset-0 col-md-12">
                                        {{form.participants}}
                                </div><!--end .col -->
                            </div><!--end .row -->
                             <!-- END MULTI-SELECT -->

                            <div class="card-actionbar">
                                <div class="card-actionbar-row">
                                    <button type="button" class="btn btn-flat btn-secundary ink-reaction">Cancelar</button>
                                    <button type="submit" class="btn btn-flat btn-primary ink-reaction">Salve</button>
                                </div>
                            </div>
                        </label>
            </form>
        </div><!--end .col -->
    </div><!--end .row -->
    <!-- END VERTICAL FORM FLOATING LABELS -->

cobradoronline/bookings/templates/bookings_create_bkp.html
<!--<form class="form-horizontal" action="{% url 'bookings:bookings_create' %}" method="post">-->
    <!--{% csrf_token %}-->
    <!--<fieldset>-->
        <!--<legend>Cadastro:</legend>-->
        <!--{% for form_field in form %}-->
            <!--<div class="form-group">-->
                <!--<label for="{{ form_field.id_for_label }}"-->
                       <!--class="col-sm-2 control-label">{{ form_field.label }}:</label>-->
                <!--<div class="col-sm-10">-->
                    <!--{{ form_field }}-->
                    <!--{{ form_field.errors }}-->
                <!--</div>-->
            <!--</div>-->
        <!--{% endfor %}-->
        <!--<div class="form-group">-->
            <!--<div class="col-sm-offset-2 col-sm-10">-->
                <!--<button type="submit" class="btn btn-primary">Criar</button>-->
            <!--</div>-->
        <!--</div>-->
    <!--</fieldset>-->
<!--</form>-->

    <!-- BEGIN VERTICAL FORM FLOATING LABELS -->
    <div class="row"> <!-- col-lg-offset-0 -->
        <div class="col-md-12">
            <form class="form" action="{% url 'bookings:bookings_create' %}" method="post">
                {% csrf_token %}
                <div class="card">
                        <div class="card-head style-primary">
                            <header>Criando agendamento</header>
                        </div>

                        <label class="card-body floating-label col-md-12">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        {{form.title.errors}}
                                        {{form.title}}
                                        <label for="{{ form.title.id_for_label}}">{{form.title.label}}</label>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="input-daterange input-group col-sm-12" id="datepicker">
                                    <div class="input-group-content">
                                        {{form.start.errors}}
                                        {{form.start}}
                                        <label for="{{form.start.id_for_label}}">{{form.start.label}}</label>
                                    </div>

                                    <span class="input-group-addon">to</span>

                                    <div class="input-group-content">
                                        {{form.end.errors}}
                                        {{form.end}}
                                        <label for="{{form.end.id_for_label}}">{{form.end.label}}</label>
                                    </div>
                                </div>
                            </div>

                            <label class="checkbox checkbox-styled">

                                <label for="{{ form.holiday.id_for_label }}" class="col-sm-3">
                                    {{ form.holiday }}
                                    {{ form.holiday.errors }}
                                    <span>{{ form.holiday.label }}</span>
                                </label>

                                <label for="{{ form.overlap.id_for_label }}" class="col-sm-3">
                                    {{ form.overlap }}
                                    {{ form.overlap.errors }}
                                    <span>{{ form.overlap.label }}</span>
                                </label>

                                <label for="{{ form.allday.id_for_label }}" class="col-sm-3">
                                    {{ form.allday }}
                                    {{ form.allday.errors }}
                                    <span>{{ form.allday.label }}</span>
                                </label>

                                <label for="{{ form.editable.id_for_label }}" class="col-sm-3">
                                    {{ form.editable }}
                                    {{ form.editable.errors }}
                                    <span>{{ form.editable.label }}</span>
                                </label>

                                <label for="{{ form.authorized.id_for_label }}" class="col-sm-3">
                                    {{ form.authorized }}
                                    {{ form.authorized.errors }}
                                    <span>{{ form.authorized.label }}</span>
                                </label>
                            </label>

                            <!-- BEGIN MULTI-SELECT -->
                            <div class="row">
                                <div class="col-lg-offset-0 col-md-12">
                                        {{form.color}}
                                </div><!--end .col -->
                            </div><!--end .row -->
                             <!-- END MULTI-SELECT -->


                            <!-- BEGIN MULTI-SELECT -->
                            <div class="row">
                                <span>{{form.participants.label}}</span>
                                <div class="col-lg-offset-0 col-md-12">
                                        {{form.participants}}
                                </div><!--end .col -->
                            </div><!--end .row -->
                             <!-- END MULTI-SELECT -->

                            <div class="card-actionbar">
                                <div class="card-actionbar-row">
                                    <button type="button" class="btn btn-flat btn-secundary ink-reaction">Cancelar</button>
                                    <button type="submit" class="btn btn-flat btn-primary ink-reaction">Salve</button>
                                </div>
                            </div>
                        </label>
                </div><!--end .card -->
            </form>
        </div><!--end .col -->
    </div><!--end .row -->
    <!-- END VERTICAL FORM FLOATING LABELS -->

cobradoronline/bookings/templates/bookings_create_form.html
<form method="post" action="{% url 'bookings:bookings_create' %}" class="js-bookings-create-form">
{% csrf_token %}
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                {{form.title.errors}}
                {{form.title}}
                <label for="{{ form.title.id_for_label}}">{{form.title.label}}</label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="input-daterange input-group" id="datepicker">
            <div class="input-group-content">
                {{form.start.errors}}
                {{form.start}}
                <label for="{{form.start.id_for_label}}">{{form.start.label}}</label>
            </div>
            <span class="input-group-addon">e</span>
            <div class="input-group-content">
                {{form.end.errors}}
                {{form.end}}
                <label for="{{form.end.id_for_label}}">{{form.end.label}}</label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-6">
            <div class="checkbox checkbox-styled">
                <label for="{{ form.holiday.id_for_label }}">
                    {{ form.holiday }}
                    <span>{{ form.holiday.label }}</span>
                </label>
            </div>
            <div class="checkbox checkbox-styled">
                <label for="{{ form.overlap.overlap }}">
                    {{ form.overlap }}
                    <span>Sobrepor</span>
                </label>
            </div>
            <div class="checkbox checkbox-styled">
                <label for="{{ form.allday.id_for_label }}">
                    {{ form.allday }}
                    <span>{{ form.allday.label }}</span>
                </label>
            </div>
        </div><!--end .col -->

        <div class="col-sm-6">
            <div class="checkbox checkbox-styled">
                <label for="{{ form.editable.id_for_label }}">
                    {{ form.editable }}
                    <span>{{ form.editable.label }}</span>
                </label>
            </div>
            <div class="checkbox checkbox-styled">
                <label for="{{ form.authorized.id_for_label }}">
                    {{ form.authorized }}
                    <span>{{ form.authorized.label }}</span>
                </label>
            </div>
        </div><!--end .col -->
    </div><!--end .form-group -->

    <div class="form-group">
        <div class="row">
            <div class="col-lg-offset-0 col-md-12">
                    {{form.color}}
            </div><!--end .col -->
        </div><!--end .row -->
    </div><!--end .form-group -->

    <div class="form-group">
        <div class="row">
            <span>{{form.participants.label}}</span>
            <div class="col-lg-offset-0 col-md-12">
                    {{form.participants}}
            </div><!--end .col -->
        </div><!--end .row -->
    </div><!--end .form-group -->

    <div class="form-group">
        <div class="card-actionbar">
            <div class="card-actionbar-row">
                <button type="button" class="btn btn-flat btn-secundary ink-reaction">Cancelar</button>
                <button type="submit" class="btn btn-flat btn-prymary ink-reaction" id="salvar">Salve</button>
            </div>
        </div>
    </div><!--end .form-group -->
</form>

<!--<script>-->
    <!--$('#multi-select').multiSelect({});-->
    <!--$('#datepicker').datepicker();-->
    <!--$('#select').select2({});-->
<!--</script>-->

cobradoronline/bookings/templates/profile_detail.html
{% extends "index.html" %}
{% load rest_framework %}
{% load static %}

{% block content %}

<h1>Profile - {{ booking.title }}</h1>

<form action="{% url 'bookings-api:update2' pk=45 %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    <input type="submit" value="Save">
</form>
{% endblock content %}

cobradoronline/bookings/templates/profile_list.html
<html><body>
<h1>Profiles</h1>
<ul>
    {% for booking in bookings %}
    <!--<li>{{ booking.user }}</li>-->
    <li>{{ booking.title }}</li>
    <li>{{ booking.start }}</li>
    <li>{{ booking.end }}</li>
    <li>{{ booking.created_on }}</li>
    <li>{{ booking.authorized }}</li>
    <li>{{ booking.color }}</li>
    <li>{{ booking.participants }}</li>
    {% endfor %}
</ul>
</body></html>